# Generated by Django 5.2.1 on 2025-09-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0002_producto_categoria_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('Compra', 'Compra'), ('Consumo', 'Consumo'), ('Devolución', 'Devolución'), ('Ajuste', 'Ajuste'), ('Venta', 'Venta')], max_length=20)),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bar_app.producto')),
            ],
        ),
    ]
