# Generated by Django 5.2.6 on 2025-10-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0004_mesa_mesera_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha',
            new_name='fecha_hora',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('confirmada', 'Confirmada')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bar_app.mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bar_app.mesera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
