# Generated by Django 5.2.6 on 2025-11-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0006_alter_pedido_mesa_alter_pedido_mesera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
