# Generated by Django 5.2.1 on 2025-12-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0007_remove_pedido_productos_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='cantidad_despachada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
