# Generated by Django 5.2.1 on 2025-12-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0009_categoria_pedidoproducto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='MANDALA DISCO CLUB', max_length=100)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje_footer', models.TextField(default='¡Gracias por su visita!')),
                ('moneda', models.CharField(default='$', max_length=10)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_hora'], name='bar_app_ped_fecha_h_57e42d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='bar_app_ped_estado_39830c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['mesera'], name='bar_app_ped_mesera__da58f7_idx'),
        ),
    ]
