# Generated by Django 5.2.1 on 2025-12-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0010_empresaconfig_alter_categoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar_app.mesera'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario'], name='bar_app_ped_usuario_1f9ec4_idx'),
        ),
    ]
