# Generated by Django 5.2.1 on 2026-01-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0011_pedido_usuario_alter_pedido_mesera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesera',
            name='codigo',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
