# Generated by Django 5.2.1 on 2026-02-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0012_alter_mesera_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='empresaconfig',
            options={'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='mesera',
            options={'ordering': ['nombre'], 'verbose_name': 'Mesera', 'verbose_name_plural': 'Meseras'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoproducto',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='empresaconfig',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar_app.pedido'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['producto', 'fecha'], name='bar_app_mov_product_fdad8d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', 'fecha'], name='bar_app_mov_tipo_9eca33_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproducto',
            index=models.Index(fields=['pedido', 'producto'], name='bar_app_ped_pedido__1560fb_idx'),
        ),
    ]
