# Generated by Django 5.2.1 on 2025-10-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0005_rename_fecha_pedido_fecha_hora_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bar_app.mesa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bar_app.mesera'),
            preserve_default=False,
        ),
    ]
