# Generated by Django 5.2.1 on 2025-11-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0006_alter_pedido_mesa_alter_pedido_mesera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado'), ('finalizada', 'Finalizada'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
